# Use an official PostgreSQL image as base
FROM postgres:latest


# Optionally, set environment variables for PostgreSQL (e.g., username, password, database name)
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

# Optionally, copy SQL scripts or initialization files to initialize the database
#COPY init.sql /docker-entrypoint-initdb.d/
